(defhydra hydra-macrostep (:foreign-keys run)
  ("e" macrostep-expand)
  ("c" macrostep-colllapse)
  ("<right>" macrostep-next-macro)
  ("<left>" macrostep-prev-macro)
  ("q" macrostep-collapse-all :exit t))
